# Generated by Django 2.1.4 on 2019-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_nessus_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_qualys_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
