# Generated by Django 2.1.4 on 2019-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20190103_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_LazyT_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
