# Generated by Django 2.1.4 on 2019-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20190103_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lazyt_progress',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
