# Generated by Django 2.1.4 on 2019-01-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_project_project_lazyt_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_created_date',
            field=models.DateField(null=True),
        ),
    ]
