# Generated by Django 2.1.4 on 2019-01-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_project_project_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_finished_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_status',
            field=models.BooleanField(null=True),
        ),
    ]
