# Generated by Django 2.1.4 on 2019-01-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20190104_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_nessus_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_qualys_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
