# Generated by Django 2.1.4 on 2019-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_auto_20190104_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_FB',
            field=models.CharField(default=12345, max_length=5),
        ),
    ]
