# Generated by Django 2.1.4 on 2019-01-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20190104_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_finished_date',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vulnerability_protocol',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vulnerability_source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_CP',
            field=models.CharField(default=12345, max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_client_company',
            field=models.CharField(default='Default Company', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_client_contact_name',
            field=models.CharField(default='Default Contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_nessus_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_qualys_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_targets',
            field=models.TextField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_test_dates',
            field=models.CharField(default='Dec 12-24th 2019', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tester_email',
            field=models.EmailField(default='jill@firstbase.co.uk', max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tester_name',
            field=models.CharField(default='Jill Ferron', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tester_phone',
            field=models.CharField(default='01234756595', max_length=11),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tester_qualifications',
            field=models.CharField(default='MSc', max_length=200),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_status',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='Target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.Target'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_outputs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_ports',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
