# Generated by Django 2.1.4 on 2019-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_vulnerability_vulnerability_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_Dradis_ID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_ports',
            field=models.TextField(),
        ),
    ]
