# Generated by Django 2.1.4 on 2019-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_auto_20190109_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='Target',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vulnerability_target',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
