# Generated by Django 2.1.4 on 2019-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_auto_20190109_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_source_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
