# Generated by Django 2.1.4 on 2019-01-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_vulnerability_vulnerability_source_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_file', models.FileField(blank=True, null=True, upload_to='')),
                ('rules_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
