# Generated by Django 2.1.4 on 2019-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_FB_name', models.CharField(max_length=500)),
                ('rule_FB_id', models.PositiveIntegerField(null=True)),
                ('rule_plugin_id', models.PositiveIntegerField(null=True)),
                ('rule_source', models.CharField(max_length=100)),
                ('rule_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
