# Generated by Django 2.1.4 on 2019-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_rule_rule_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_rules_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
