# Generated by Django 2.1.4 on 2019-01-18 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_rule_rule_rules_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_FB_name', models.CharField(max_length=500)),
                ('rule_nessus_plugin_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('rule_qualys_plugin_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('rule_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
