# Generated by Django 2.1.4 on 2019-01-18 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_fbrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbrule',
            name='rule_nessus_plugin_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='fbrule',
            name='rule_qualys_plugin_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
